[phases.build]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]
aptPkgs = ["build-essential"]

[phases.install]
commands = [
    "python -m venv .venv",
    ". .venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". .venv/bin/activate && uvicorn bot:web_app --host 0.0.0.0 --port $PORT"
